POST http://localhost:3000/campaigns

{
    "Name": "teste",
    "Content":"teste com body",
    "emails": ["teste@gmail.com"]
}

###  
GET http://localhost:3000/campaigns/cmseqnplrn0ko10278s0

###  
PATCH  http://localhost:3000/campaigns/cancel/cmseqnplrn0ko10278s0

